name: Java CI

on:
  push:
  schedule: [ cron: '17 3 * * 5' ] # weekly: At 02:42 on Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn verify
